-- V-007: the inbound webhook (P0-6). Generated by `prisma migrate diff`,
-- then hand-edited: everything below the HAND-WRITTEN marker is what Prisma
-- cannot express.

-- AlterTable
ALTER TABLE "OutboundMessage" ADD COLUMN     "inboundMessageId" BIGINT,
ALTER COLUMN "reservationId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ReservationEvent" ADD COLUMN     "inboundMessageId" BIGINT;

-- CreateTable
CREATE TABLE "InboundMessage" (
    "id" BIGSERIAL NOT NULL,
    "providerMessageId" TEXT NOT NULL,
    "fromPhone" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "receivedAt" TIMESTAMPTZ(3) NOT NULL,
    "outcome" TEXT NOT NULL,
    "reservationId" UUID,
    "choices" TEXT[] DEFAULT ARRAY[]::TEXT[],

    CONSTRAINT "InboundMessage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SmsOptOut" (
    "phone" TEXT NOT NULL,
    "at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "SmsOptOut_pkey" PRIMARY KEY ("phone")
);

-- CreateIndex
CREATE UNIQUE INDEX "InboundMessage_providerMessageId_key" ON "InboundMessage"("providerMessageId");

-- CreateIndex
CREATE INDEX "InboundMessage_fromPhone_id_idx" ON "InboundMessage"("fromPhone", "id");

-- CreateIndex
CREATE UNIQUE INDEX "OutboundMessage_inboundMessageId_key" ON "OutboundMessage"("inboundMessageId");

-- AddForeignKey
ALTER TABLE "ReservationEvent" ADD CONSTRAINT "ReservationEvent_inboundMessageId_fkey" FOREIGN KEY ("inboundMessageId") REFERENCES "InboundMessage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OutboundMessage" ADD CONSTRAINT "OutboundMessage_inboundMessageId_fkey" FOREIGN KEY ("inboundMessageId") REFERENCES "InboundMessage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InboundMessage" ADD CONSTRAINT "InboundMessage_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;



-- ═══ HAND-WRITTEN ═══════════════════════════════════════════════════════════

-- The lists mirror MESSAGE_KINDS and INBOUND_OUTCOMES in packages/core.
ALTER TABLE "OutboundMessage"
  DROP CONSTRAINT outbound_kind_known,
  ADD CONSTRAINT outbound_kind_known CHECK ("kind" IN (
    'confirmation', 'confirmed', 'cancelled', 'change_link', 'choose',
    'no_reservation', 'unrecognised', 'help', 'opted_out')),
  -- A message belongs to its reservation (the confirmation) or to the
  -- inbound text it answers (a reply) — never neither, never both. Replies
  -- are not one-per-(reservation, kind): a guest may text C twice.
  ADD CONSTRAINT outbound_one_owner CHECK (num_nonnulls("reservationId", "inboundMessageId") = 1);

ALTER TABLE "InboundMessage"
  ADD CONSTRAINT inbound_outcome_known CHECK ("outcome" IN (
    'opted_out', 'opted_in', 'help', 'confirmed', 'cancelled', 'change_link',
    'choose', 'selected', 'no_reservation', 'unrecognised', 'handoff')),
  -- Ten concatenated segments is the most a carrier delivers as one message.
  ADD CONSTRAINT inbound_body_max_1600 CHECK (char_length("body") <= 1600);

-- Same pattern as ReservationEvent: the inbound log is evidence, and evidence
-- is never edited. TRUNCATE (the test reset) fires no row trigger.
CREATE OR REPLACE FUNCTION inbound_message_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'InboundMessage is append-only: % is not permitted (message %).', TG_OP, OLD."providerMessageId";
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER inbound_message_append_only
  BEFORE UPDATE OR DELETE ON "InboundMessage"
  FOR EACH ROW EXECUTE FUNCTION inbound_message_append_only();
