-- V-003: reservation model. Generated by `prisma migrate dev --create-only`,
-- then hand-edited: everything below the HAND-WRITTEN marker is what Prisma
-- cannot express.

-- A gist index over a plain text column (TableHold.tableId WITH =) needs the
-- btree operator classes. Created before the tables so the whole migration
-- applies top to bottom on a from-scratch database.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- CreateTable
CREATE TABLE "DiningTable" (
    "id" TEXT NOT NULL,
    "seats" INTEGER NOT NULL,
    "minParty" INTEGER NOT NULL,
    "section" TEXT NOT NULL,

    CONSTRAINT "DiningTable_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Combination" (
    "id" TEXT NOT NULL,
    "seats" INTEGER NOT NULL,
    "minParty" INTEGER NOT NULL,

    CONSTRAINT "Combination_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CombinationMember" (
    "combinationId" TEXT NOT NULL,
    "tableId" TEXT NOT NULL,

    CONSTRAINT "CombinationMember_pkey" PRIMARY KEY ("combinationId","tableId")
);

-- CreateTable
CREATE TABLE "Reservation" (
    "id" UUID NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "businessDay" TEXT NOT NULL,
    "startAt" TIMESTAMPTZ(3) NOT NULL,
    "partySize" INTEGER NOT NULL,
    "turnMinutes" INTEGER NOT NULL,
    "tableIds" TEXT[],
    "guestName" TEXT NOT NULL,
    "guestPhone" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL,
    "statusChangedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Reservation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TableHold" (
    "reservationId" UUID NOT NULL,
    "tableId" TEXT NOT NULL,
    "startAt" TIMESTAMPTZ(3) NOT NULL,
    "endAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "TableHold_pkey" PRIMARY KEY ("reservationId","tableId")
);

-- CreateTable
CREATE TABLE "ReservationEvent" (
    "id" BIGSERIAL NOT NULL,
    "reservationId" UUID NOT NULL,
    "at" TIMESTAMPTZ(3) NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "note" TEXT,

    CONSTRAINT "ReservationEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Reservation_idempotencyKey_key" ON "Reservation"("idempotencyKey");

-- CreateIndex
CREATE INDEX "Reservation_businessDay_startAt_idx" ON "Reservation"("businessDay", "startAt");

-- CreateIndex
CREATE INDEX "Reservation_guestPhone_idx" ON "Reservation"("guestPhone");

-- CreateIndex
CREATE INDEX "ReservationEvent_reservationId_at_idx" ON "ReservationEvent"("reservationId", "at");

-- AddForeignKey
ALTER TABLE "CombinationMember" ADD CONSTRAINT "CombinationMember_combinationId_fkey" FOREIGN KEY ("combinationId") REFERENCES "Combination"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CombinationMember" ADD CONSTRAINT "CombinationMember_tableId_fkey" FOREIGN KEY ("tableId") REFERENCES "DiningTable"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TableHold" ADD CONSTRAINT "TableHold_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TableHold" ADD CONSTRAINT "TableHold_tableId_fkey" FOREIGN KEY ("tableId") REFERENCES "DiningTable"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationEvent" ADD CONSTRAINT "ReservationEvent_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ═══ HAND-WRITTEN ═══════════════════════════════════════════════════════════

-- THE allocation constraint (P0-3). One party per table per instant. Turns
-- vary by party size, so overlapping windows are not EQUAL windows and a
-- UNIQUE index cannot see the collision — `&&` on a half-open range can. A
-- 7:00-8:30 hold and an 8:30-10:00 hold on the same table do not overlap.
-- A combination writes one row per member table, so booking [T4,T5] collides
-- with a deuce already on T5. Violation: SQLSTATE 23P01, which placement
-- (V-005) maps to a clean refusal.
ALTER TABLE "TableHold"
  ADD CONSTRAINT table_hold_no_overlap
  EXCLUDE USING gist ("tableId" WITH =, tstzrange("startAt", "endAt", '[)') WITH &&);

ALTER TABLE "TableHold"
  ADD CONSTRAINT table_hold_window_positive CHECK ("endAt" > "startAt");

ALTER TABLE "Reservation"
  ADD CONSTRAINT reservation_party_positive CHECK ("partySize" > 0),
  ADD CONSTRAINT reservation_turn_positive CHECK ("turnMinutes" > 0),
  ADD CONSTRAINT reservation_has_tables CHECK (cardinality("tableIds") > 0);

-- Same pattern as Countertop's OrderEvent. TRUNCATE is deliberately NOT
-- blocked: it fires TRUNCATE triggers, not row triggers, and it is how the
-- test suite resets between files. Nothing in the application issues one.
CREATE OR REPLACE FUNCTION reservation_event_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'ReservationEvent is append-only: % is not permitted (reservation %). Write a revert event instead.',
    TG_OP, OLD."reservationId";
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER reservation_event_append_only
  BEFORE UPDATE OR DELETE ON "ReservationEvent"
  FOR EACH ROW EXECUTE FUNCTION reservation_event_append_only();
